-- Sample data for teachers_authority table
INSERT INTO teachers_authority (name, role, bio, image_url, profile_url) VALUES
('Dr. Sarah Johnson', 'Dean of Academic Affairs', 'Dr. Sarah Johnson has over 20 years of experience in higher education administration. She specializes in curriculum development and academic policy implementation.', '/static/images/faculty/sarah-johnson.jpg', '/faculty/sarah-johnson'),
('Prof. Michael Chen', 'Head of Computer Science', 'Professor Chen is a leading expert in artificial intelligence and machine learning. He has published numerous papers in top-tier conferences and journals.', '/static/images/faculty/michael-chen.jpg', '/faculty/michael-chen'),
('Dr. Emily Rodriguez', 'Director of Student Services', 'Dr. Rodriguez focuses on student success and retention. She oversees counseling services, career development, and student support programs.', '/static/images/faculty/emily-rodriguez.jpg', '/faculty/emily-rodriguez'),
('Prof. David Thompson', 'Chair of Business Administration', 'Professor Thompson brings extensive industry experience to the classroom. His research focuses on entrepreneurship and strategic management.', '/static/images/faculty/david-thompson.jpg', '/faculty/david-thompson'),
('Dr. Lisa Park', 'Research Director', 'Dr. Park leads the university research initiatives and manages grant applications. She has secured over $5 million in research funding.', '/static/images/faculty/lisa-park.jpg', '/faculty/lisa-park'),
('Prof. James Wilson', 'Head of Engineering', 'Professor Wilson specializes in mechanical engineering and sustainable design. He has patented several innovative engineering solutions.', '/static/images/faculty/james-wilson.jpg', '/faculty/james-wilson'),
('Dr. Maria Garcia', 'Library Director', 'Dr. Garcia oversees the university library system and digital resources. She is passionate about information literacy and open access initiatives.', '/static/images/faculty/maria-garcia.jpg', '/faculty/maria-garcia'),
('Prof. Robert Kim', 'Director of International Programs', 'Professor Kim manages international partnerships and student exchange programs. He has facilitated collaborations with universities in over 20 countries.', '/static/images/faculty/robert-kim.jpg', '/faculty/robert-kim'),
('Dr. Jennifer Liu', 'Head of Humanities', 'Dr. Liu specializes in literature and cultural studies. Her work explores the intersection of technology and humanities in the digital age.', '/static/images/faculty/jennifer-liu.jpg', '/faculty/jennifer-liu'),
('Prof. Thomas Anderson', 'Athletic Director', 'Professor Anderson oversees all athletic programs and facilities. He is committed to developing well-rounded student-athletes.', '/static/images/faculty/thomas-anderson.jpg', '/faculty/thomas-anderson'),
('Dr. Rachel Green', 'Director of Admissions', 'Dr. Green leads the admissions team and develops recruitment strategies. She is dedicated to making higher education accessible to all qualified students.', '/static/images/faculty/rachel-green.jpg', '/faculty/rachel-green'),
('Prof. Kevin Brown', 'Chief Information Officer', 'Professor Brown manages the university technology infrastructure and digital transformation initiatives.', '/static/images/faculty/kevin-brown.jpg', '/faculty/kevin-brown');

-- Sample data for campus_landscapes table
INSERT INTO campus_landscapes (title, subtitle, description, image_url, link_url) VALUES
('Main Library Building', 'State-of-the-Art Learning Hub', 'A state-of-the-art library facility spanning three floors with over 500,000 volumes, study spaces, and digital resources. Features modern architecture with glass facades and sustainable design elements.', '/static/images/campus/library.jpg', '/campus/library'),
('Science and Technology Center', 'Advanced Research Facility', 'A cutting-edge research facility housing laboratories for physics, chemistry, and biology. Equipped with advanced research equipment and collaborative workspaces for interdisciplinary studies.', '/static/images/campus/science-center.jpg', '/campus/science-center'),
('Student Union Building', 'Heart of Campus Life', 'The heart of campus life featuring dining halls, recreational areas, student organizations offices, and performance spaces. A hub for social activities and community engagement.', '/static/images/campus/student-union.jpg', '/campus/student-union'),
('Athletic Complex', 'Comprehensive Sports Facilities', 'A comprehensive sports facility including a main gymnasium, swimming pool, fitness center, and outdoor fields. Supports both competitive sports and recreational activities.', '/static/images/campus/athletic-complex.jpg', '/campus/athletics'),
('Botanical Gardens', 'Peaceful Learning Environment', 'Beautiful landscaped gardens spanning 50 acres featuring native plants, walking paths, and educational exhibits. A peaceful retreat for students and a living laboratory for biology students.', '/static/images/campus/botanical-gardens.jpg', '/campus/gardens'),
('Innovation Hub', 'Entrepreneurship Center', 'A collaborative workspace for entrepreneurship and innovation featuring maker spaces, 3D printers, and startup incubation programs. Connects students with industry partners.', '/static/images/campus/innovation-hub.jpg', '/campus/innovation'),
('Performing Arts Center', 'Cultural Performance Venue', 'A 1,200-seat theater and concert hall hosting performances, lectures, and cultural events. Features professional lighting and sound systems.', '/static/images/campus/arts-center.jpg', '/campus/arts'),
('Residential Village', 'Modern Student Housing', 'Modern student housing with apartment-style living, community spaces, and on-site amenities. Provides a supportive living-learning environment.', '/static/images/campus/residential-village.jpg', '/campus/housing'),
('Sustainability Park', 'Eco-Friendly Learning Space', 'An eco-friendly park demonstrating sustainable practices including solar panels, rainwater collection, and native plant landscaping. Serves as an outdoor classroom.', '/static/images/campus/sustainability-park.jpg', '/campus/sustainability'),
('Research Greenhouse', 'Botanical Research Facility', 'A climate-controlled greenhouse facility for botanical research and education. Features specialized growing areas and research laboratories.', '/static/images/campus/greenhouse.jpg', '/campus/greenhouse');